Dev
stepgazaille/qbsum pull request #1
Opened 2018-11-06 17:15 UTC by stepgazaille

New MMR query-based summarization algorithm implementation.

2018-11-12 19:10 UTC, ldacosta requested changes
- [ ] Implementer tests decrits dans commentaire sur fichier `summarizers.py`

2018-11-12 19:10 UTC, ldacosta commented on qbsum/summarizers.py
>  import os
Ce serait important d'ajouter des fonctions de test pour ton code - la revue serait plus simple et ce serait plus facile à maintenir. Dans ce module je pense que ce serait impératif d'avoir des tests pour `__similarity` et `__count_words`; le test pour `summarize ` est plus délicat et tu peux choisir si le faire dans cette p-r ou plus tard (en même temps les cas de base: "query vide", etc., ne seraient pas trop durs à implémenter. En tout cas, tu peux choisir si le faire maintenant ou non)

2018-11-12 19:10 UTC, ldacosta commented on qbsum/summarizers.py
> +# Original implementation: https://www.quora.com/Where-can-I-find-a-maximum-marginal-relevance-algorithm-in-Python-for-redundancy-removal-in-two-documents
ok! Aussi: http://www.cs.bilkent.edu.tr/~canf/CS533/hwSpring14/eightMinPresentations/handoutMMR.pdf

2018-11-13 17:48 UTC, stepgazaille commented on qbsum/summarizers.py
>  import os
Addressed in 699faf67273c7315372ec32c16e77f92475b8a54

2018-11-15 14:24 UTC, ldacosta commented on .travis.yml
> +    - dev
Good stuff!

2018-11-15 14:25 UTC, ldacosta commented
@stepgazaille commented on https://github.com/stepgazaille/qbsum/commit/699faf67273c7315372ec32c16e77f92475b8a54 ; maybe I am confused?

2018-11-15 18:20 UTC, ldacosta commented on qbsum/summarizers.py
> +        :return: similarity score
dans quel rang? Avec quelle sémantique? (je vois que c'est la même sémantique que dans `spacy`, mais juste parce que j'ai suivi ton code. Donc, je propose, eg, 
```suggestion
        :return: similarity score, in [0,1], where 1 == perfect similarity.
```
)

2018-11-15 18:20 UTC, ldacosta commented on tests/test_summarizer.py
> +        self.assertTrue(score > 0.6)
voir commentaire dans `__similarity`; à ce point-ci, je me demande pourquoi ce n'est pas 
```suggestion
        self.assertTrue(score == 1.0)
```

2018-11-15 18:20 UTC, ldacosta commented on tests/test_summarizer.py
> +        self.assertTrue(score < 0.4)
voir commentaire dans __similarity; à ce point-ci, je me demande pourquoi `0.4`

2018-11-15 18:20 UTC, ldacosta submitted a review, later dismissed

2018-11-15 18:21 UTC, ldacosta commented
- [ ] clarifier la sémantique de `__similarity`

2018-11-15 18:45 UTC, ldacosta approved these changes

2018-11-15 18:53 UTC, merged